#应用(服务)名称
spring:
  application:
    name: service-provider
#DB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#JPA
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
server:
  port: 8081
#注册中心地址
eureka:
  client:
     serviceUrl:
        defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/
  instance:
      instance-id: dept-8081.com
      prefer-ip-address: true
#info
info:
  app.name: service-provider
  company.name: chengql
  build.artifactId: $project.artifactId$
  build.version: $project.version$