spring:
  application:
    name: api-gateway
server:
  port: 8888
zuul:
  routes:
    test:
      path: /aaa/**
      url: service-provider

eureka:
  client:
     serviceUrl:
        defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/